### PR TITLE
fix(cli): incorrect import paths

### LINKED ISSUE #81: Bug: buildPath returning incorrect path
ontology_debug

buildPath is returning `node_modules/@zazuko/ontologies` instead of the correct `node_modules/@zazuko/rdf-vocabularies/ontologies`.

Additionally, the `vocabularies()` function should properly throw an error if it reads files in the wrong location.

Thanks for this tool!

### PR DESCRIPTION
**Pull request by tpluscode**
Turns out that some paths were not updated since last code reorganisation

I've also added a simple sanity check to CI which runs the CLI

#fixes #81

### CODE REVIEW

File: src/loadDataset/index.ts [hunk 1]
```diff
@@ -1,11 +1,14 @@
...
+import pkgDir from 'pkg-dir'
 import { join, resolve } from 'path'
 import type prefixes from '../prefixes'
 
-function buildPath (prefix: keyof typeof prefixes) {
-  return resolve(join(__dirname, '../../ontologies', `${prefix}.nq`))
+async function buildPath (prefix: keyof typeof prefixes) {
+  const rootDir = await pkgDir(__dirname)
+  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+  return resolve(join(rootDir!, 'ontologies', `${prefix}.nq`))
```
Comment (tpluscode) [inline src/loadDataset/index.ts:9]: The path is different in dev (`src`) and in deployed node_modules, when the JS file reside in package root.

Using `pkg-dir` seems like the easiest way to normalise the relative path to the package root dir

**Review by vhf — APPROVED** [review]
